language: python

sudo: false

python:
  - "3.4"
  - "3.5"
  - "3.6"

cache:
    pip: true

before_install:
    - pip install -U pip

install:
    - pip install -r requirements.txt

script:
    - nosetests
